### ISSUE TITLE
Submit to homebrew/core

### ISSUE THREAD

**Issue by zmwangx** [sinclairtarget/um#14]
`um` is popular enough for a core formula, so why not submit it to core and make it easier for everyone? I can handle the grunt work of fixing it up to pass audits, having it submitted and seeing it through if you don't want to do that yourself.

**Comment by sinclairtarget** [comment]
You're right! This hadn't even occurred to me. I'll take a look at what this would involve. Thanks for suggesting it.

**Comment by sinclairtarget** [comment]
@zmwangx Hoping to replace pandoc with a gem before this happens, but this is still on my radar.

**Comment by zmwangx** [comment]
No problem! Thanks for the update, and please take your time.

**Comment by sinclairtarget** [comment]
If anyone here is keen to see this happen, maybe let the Homebrew maintainers known in https://github.com/Homebrew/homebrew-core/pull/32670? Not sure how they decide which PRs get merged and which languish

**Comment by zmwangx** [comment]
Hmm, back when I was on the maintainer team (a long time ago), green new formula PRs with no additional complaints were either rejected fairly quickly or merged within maybe three days... Maybe just need a ping...

**Comment by sinclairtarget** [comment]
Woo hoo! Thanks for the ping.

https://github.com/Homebrew/homebrew-core/commit/4e0ce9a807800777f4d17a21578c016ca706a09b
