### ISSUE TITLE
cannot run um

### ISSUE THREAD

**Issue by navdeepio** [sinclairtarget/um#24]
Issuing `um <arg>` results in the following error.
```
Traceback (most recent call last):
	8: from /usr/bin/um:23:in `<main>'
	7: from /usr/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
	6: from /usr/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
	5: from /usr/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
	4: from /usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	3: from /usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	2: from /usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	1: from /usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
/usr/lib/ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'kramdown' (~> 1.17) - did find: [kramdown-2.1.0,kramdown-2.0.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/home/nav/.gem/ruby/2.6.0:/usr/lib/ruby/gems/2.6.0:/home/nav/.gem', execute `gem env` for more information
```
OS: ArchLinux

**Comment by sinclairtarget** [comment]
It looks like you've got more recent versions of the Kramdown gem than um expects. What happens if you uninstall and reinstall um? I would have thought that would reinstall the needed version of Kramdown.

**Comment by navdeepio** [comment]
I get the same error.. 

Dependent on the AUR package, so I suppose the version mismatch originates there..

**Comment by iajrz** [comment]
@He-Ro you may want to see this. <3

**Comment by iajrz** [comment]
(Unless I'm sorely mistaken, @He-Ro made sure um was available in both linuxbrew and AUR.

**Comment by He-Ro** [comment]
So there is a kramdown-1 package in the AUR: https://aur.archlinux.org/packages/ruby-kramdown-1/ Does `um` really only work with kramdown version 1? Then changing the dependency in the PKGBUILD to this kramdown version should be the solution. Will try it out myself, but I don't know when I have time for that.

**Comment by He-Ro** [comment]
@navdeepio I updated the AUR package. It should work if you rebuild it now. Let me know if it is still broken. You can also use the AUR comments for that if you want.

**Comment by navdeepio** [comment]
it appears there's a typo in the pkgbuild (never wrote one before so don't know), the build is still failing with `error: target not found: ruby-kramdown=1.17.0`

I went on to install ruby-kramdown-1 and then rebuilt um.. and it works now.

**Comment by iajrz** [comment]
@navdeepio I am not an Arch user, so I don't completely grasp the current situation. You mean you still can't install from AUR because of the dependency issue, but found a workaround by manually installing the dependency?

**Comment by navdeepio** [comment]
@iajrz precisely.

**Comment by iajrz** [comment]
@He-Ro what would be a good place to track this particular issue? This isn't an `um` issue, but an AUR packaging issue 😄

**Comment by He-Ro** [comment]
As I said, the comments of the AUR package are typically used for this. I have to read a little about dependency resolution in order to understand if depending directly on `ruby-kramdown-1` is the correct approach.
@navdeepio are you using a AUR helper? If yes, could you tell me which one?

**Comment by iajrz** [comment]
I was hoping you could share a URL or -- properly help @navdeepio use the right mechanism, so that this discussion could be moved there and this issue closed 😅

**Comment by He-Ro** [comment]
Right here: https://aur.archlinux.org/packages/um/

**Comment by sinclairtarget** [comment]
Thanks so much @He-Ro for sorting this out. Let me know if you need anything from me
