### ISSUE TITLE
How to set default editor to emacs with options (emacs -nw -q)

### ISSUE THREAD

**Issue by sbilmis** [sinclairtarget/um#25]
Hi,
This is not a bug but just asking for help.

I can change the default editor to emacs. However, in that case it opens with a gui. I want it to be opened in terminal. Hence, try to set editor as editor = emacs -nw -q but this does not work. Is there any solution for this?

Thanks in advance.

**Comment by sinclairtarget** [comment]
Hey! This is my fault. You should be able to do this. I think I know what the problem is and I hope to get around to fixing it at some point.

In the meantime, if you set a shell alias, say something like `emacsnogui`, and then have um use that, I bet that would work.

**Comment by sbilmis** [comment]
Hi, 
I already tried that. I use the `alias es='emacs -nw -q' `in my .bash_profile. I changed the line `editor = es `in umconfig, however, I get the error message "sh: es: command not found".

**Comment by sinclairtarget** [comment]
I've just pushed a new release (4.2.0) that should fix this issue. May be a while until it become available in Homebrew or whatever package manager you are using.
