### ISSUE TITLE
Can't install on Ubuntu

### ISSUE THREAD

**Issue by meygerjos** [sinclairtarget/um#26]
I just tried to install `um` with the following instructions (from [this thread](https://news.ycombinator.com/item?id=17797355)):

> Installing this on Linux is straightforward.
> 1. You need Pandoc. On Debian, Ubuntu, etc. this is: `sudo apt-get install pandoc`. I'm sure there's a similar incantation for Arch and so forth, but I can't be arsed. If you don't already have Ruby installed in your system, you'll need that too.
> 
> 2. cd into your favorite personal toolbox directory and `git clone https://github.com/sinclairtarget/um.git`
> 
> 3. Add a symlink to um in /usr/local/bin: `sudo ln -s /your/path/to/um/bin/um /usr/local/bin/um`. Make sure you're symlinking to the um script, not the um directory.
> 
> That's it. Enjoy.
> 
> Nice little widget. I like it.

Now when I try to run it, I get the following error message:

> 2: from /usr/local/bin/um:3:in `<main>'
> 1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
> /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- um (LoadError)

What should I do?

I am running Ubuntu 18.04.

Thanks!

**Comment by sinclairtarget** [comment]
IMO, it's much better to use a package manager to install Um. But if you want to go the git clone route, run the following in the um directory:

```
$ gem build um.gemspec && gem install um*.gem
```

You can then symlink to the um executable like before. The above installs um as a gem so that the require works.
