### ISSUE TITLE
Get help pages from multiple sources

### ISSUE THREAD

**Issue by robinbowes** [sinclairtarget/um#28]
Can `um` look for help pages in multiple locations? I'm thinking something like `MANPATH`.

The use-case would be creating a set of docs/pages to share between several users (eg. team members), whilst maintaining the capability to create personal help pages.

**Comment by sinclairtarget** [comment]
This is a cool idea! Um can't do that now, but I don't think it would be too difficult to add if you wanted to give it a go. I don't have the bandwidth at the moment unfortunately.
