### ISSUE TITLE
Update ruby version

### ISSUE THREAD

**Issue by ChillerDragon** [sinclairtarget/um#29]
```
WARNING: ruby-2.2.3 is past its end of life and is now unsupported.

/usr/include/openssl/asn1_mac.h:10:2: error: #error "This file is obsolete; please update your software."
 #error "This file is obsolete; please update your software."
  ^~~~~
```

**Comment by sinclairtarget** [comment]
Um doesn't specify a particular version of Ruby. If you install it via Homebrew, for example, Homebrew will just satisfy the Ruby dependency with the latest Ruby.

It previously had a `.ruby-version` file, but that was only meant for development. It didn't make that much sense even then so I've now removed it. See https://github.com/sinclairtarget/um/commit/a0e82e1b02c7c9e5a63463e4e4e8a4ba0080b734
