### ISSUE TITLE
Missing AUR dependency ruby-kramdown-1

### ISSUE THREAD

**Issue by arnestrathmann** [sinclairtarget/um#30]
Hi, I am using Manjaro Linux and would like to install Um, but the 'ruby-kramdown-1' AUR dependency is gone. 404 on https://aur.archlinux.org/packages/ruby-kramdown-1/.
I have no knowledge about how AUR works. Is there anything I can do to fix this or can I assist in any way?
Thanks in advance!

**Comment by He-Ro** [comment]
https://aur.archlinux.org/packages/um/ has been updated to not require version 1.17 of kramdown but instead uses the current version of kramdown.

For this a patch was needed for um, so there might be problems with this. But it should now build again.

**Comment by arnestrathmann** [comment]
Thanks for the update!
