### ISSUE TITLE
windows port

### ISSUE THREAD

**Issue by neocris** [sinclairtarget/um#4]
any plans to port this to windows?

**Comment by neocris** [comment]
incidently, i've been reading [this post](https://twobithistory.org/2017/09/28/the-lineage-of-man.html) that gives some clues to the issue

**Comment by sinclairtarget** [comment]
@iajrz Definitely using um to maintain text files should work. Can you install `man` on windows though?

**Comment by iajrz** [comment]
Last time I installed Cygwin (a decade ago, give or take) it included man.

Yet I _think_ interest in using `um` in a Windows environment is rather limited to non-existent, though. Given no follow-ups and, most crucially, no testing volunteers - I'd probably close this issue.
 
Windows 10 users [can use Linuxbrew in WSL](https://github.com/Linuxbrew/brew/wiki/Windows). Given the givens, that might be a good official answer.

**Comment by sinclairtarget** [comment]
Absent a choco package, that seems to be the best option ^
