### ISSUE TITLE
Config location

### ISSUE THREAD

**Issue by OJFord** [sinclairtarget/um#5]
Could you please consider respecting [$XDG_CONFIG_HOME](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)?

That is, storing the config in the first of these where the env var exists:
- $UM_CONFIG_HOME
- $XDG_CONFIG_HOME/um
- $HOME/.config/um

Alternatively, in order not to change anything for users already using $HOME/.um, simply use XDG_CONFIG_HOME if it's set (since then the user surely wants it to be used) and carry on with existing behaviour otherwise.

Many thanks for um - a simple but great idea!

**Comment by sinclairtarget** [comment]
This kinda blew up on Hacker News randomly and I haven't worked on it for a while. But you're welcome to submit a PR! It's a very simple project and should be easy to change.

Glad you like it!

**Comment by masukomi** [comment]
was just about to submit a ticket with the same request. 

that being said, it should probably _continue_ to support `~/.um` as the final fallback for anyone who already has it installed and configured.

**Comment by sinclairtarget** [comment]
I've added support for a `UMCONFIG_HOME` env var that functions just as you suggested. See a7cedd065be5471ab851d01b5c566b202f72ab5c, which is available in the 3.1.0 release.

You're welcome to add support for `XDG_CONFIG_HOME` but that will require more work. Paths starting with `~` are expanded in a bunch of different places by Ruby's `File::expand_path`, which as far as I know does not respect `XDG_CONFIG_HOME`.

**Comment by OJFord** [comment]
Closing as I tend to consider `$[TOOL]_CONFIG_HOME`s 'good enough' in the quest/losing battle for global `$XDG_CONFIG_HOME` support 🙂.
